---

- name: Patch the host server
  hosts: nexus_server
  become: true

  tasks:
    - name: Update host os
      yum:
        name: '*'
        state: latest

    - name: Install java and net-tools
      yum:
        name:
          - java-1.8.0-openjdk
          - net-tools
    
- name: Download nexus and unzip nexus
  hosts: nexus_server
  become: true

  tasks:
    - name: Check nexus folder stats
      stat:
        path: /opt/nexus
      register: stat_result

    - name: Download nexus
      get_url:
        url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
        dest: /opt/
      register: download_result
      when: 
        - not stat_result.stat.exists

    - name: Unpack downloaded tar file
      unarchive:
        src: "{{download_result.dest}}"
        dest: /opt/
        remote_src: true
      when: 
        - not stat_result.stat.exists

    - name: Find nexus folder
      find:
        paths: /opt/
        pattern: "nexus-*"
        file_type: directory
      register: find_result

    - name: Rename nexus folder
      shell:
        cmd: mv {{find_result.files[0].path}} /opt/nexus
      when: 
        - not stat_result.stat.exists

- name: Add user and change ownership
  hosts: nexus_server
  become: true

  tasks:

    - name: Make sure nexus group exists
      group:
        name: nexus
        state: present

    - name: Create user nexus
      user:
        name: nexus
        group: nexus
        comment: nexus user
    
    - name: Change nexus file ownership
      file:
        path: /opt/nexus
        state: directory
        recurse: yes
        owner: nexus
        group: nexus

    - name: Change sonatype-work file ownership
      file:
        path: /opt/sonatype-work
        state: directory
        recurse: yes
        owner: nexus
        group: nexus

- name: Start nexus with nexus user
  hosts: nexus_server
  become: true
  become_user: nexus

  tasks:
    - name: Set run_as_user nexus
      lineinfile:
        path: /opt/nexus/bin/nexus.rc
        regexp: '^#run_as_user=""'
        line: run_as_user="nexus"
  
    - name: Start nexus
      command:
        cmd: /opt/nexus/bin/nexus start

    - name: Ensure nexus is running
      shell:
        cmd: ps aux | grep nexus
      register: nexus_status

    - name: Show the result
      debug:
        var: nexus_status.stdout_lines

- name: Configure the Firewall
  hosts: nexus_server
  become: true

  tasks:
  
    - name: Open nexus port on firewalld
      firewalld:
        port: 8081/tcp
        permanent: yes
        state: enabled
    
    - name: reload service firewalld
      systemd:
        name: firewalld
        state: reloaded